urls.py
from django.conf.urls.defaults import patterns, include, url
from envaya import views

urlpatterns = patterns('',
	url(r'^/', 'envaya.views.home'),
	url(r'^admin/', 'envaya.views.admin'),
)

models.py
from django.db import models

# TODO(diopib) : handle the timestamp
# TODO(diopib) : handle message types (sms, mms, call)
# TODO(diopib) : handle action = outgoing
# TODO(diopib) : handle action = forward_send
# TODO(diopib) : handle action = amqp_started
# TODO(diopib) : handle event = cancel
# TODO(diopib) : handle event = cancel_all
# TODO(diopib) : handle event = settings

class Request(models.Model):
	"""model describing the connection with envaya server"""

	created_at = models.DateTimeField(auto_now_add = True)


class Response(models.Model):
	"""model describing the connection with envaya server"""


class Rule(models.Model):
	"""different rules to handle request from envaya server"""

	in_request = models.ForeignKey(Request)
	out_response = models.ForeignKey(Response)


class BasicRule(models.Model):
	"""basic rule model : incoming text, outgoing text"""

	name = models.CharField(max_length=50)
	in_text = models.CharField(max_length=150)
	out_text = models.CharField(max_length=140)


# BEG : defining requests ###############################################################

class Incoming(Request):
	"""defining model for an incoming sms"""

	from_number = models.CharField(max_length=15)
	message_content = models.CharField(max_length=1000)


class Message_status(Request):
	"""defining models for send status com"""

	# choices defining the message send status
	SEND_STATUS_CHOICES = (
		('QUEUED', 'queued'),
		('FAILED', 'failed'),
		('CANCEL', 'cancelled'),
		('SENT' , 'sent'),
		)

	mess_id = models.CharField(max_length=100)
	mess_status = models.CharField(max_length=6, choices=SEND_STATUS_CHOICES)
	error = models.CharField(max_length=500)


class Device_status(Request):
	"""defining models for device status com"""

	# choices defining the device status
	DEVICE_STATUS_CHOICES = (
		('POW_CON', 'Power Connected'),
		('POW_DIS', 'Power Disconnected'),
		('BAT_OK', 'Battery OK'),
		('BAT_LOW' , 'Battery Low'),
		('SEND_LIM', 'send Limit Exceeded'),
		)

	dev_status = models.CharField(max_length=8, choices=DEVICE_STATUS_CHOICES)

# END : defining requests ###############################################################

# BEG : defining responses ##############################################################

class Send(Response):
	"""model for sending message com"""

	to_number = models.CharField(max_length=15)
	message_content = models.CharField(max_length=160)

class Log(Response):
	"""models for printing a log message in envaya server"""

	log_message = models.CharField(max_length=100)

class Error(Response):
	"""semding an error message to be displayed in envaya"""

	error_message = models.CharField(max_length=100)

# END : defining responses ##############################################################

forms.py
from django.forms import ModelForm
from django.forms import Textarea 
from envaya.models import *

class BasicRuleForm(ModelForm):
	class Meta:
		model = BasicRule
		"""widgets = {
			'in_text' : Textarea(attrs={'cols': 10, 'rows': 20}),
			'out_text' : Textarea(attrs={'cols': 50, 'rows': 20}),
		}"""

views.py
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseRedirect, HttpResponseNotFound, HttpResponseBadRequest
from django.shortcuts import RequestContext, render_to_response
from django.template import loader
from random import choice
from forms import BasicRuleForm
from models import BasicRule


from envaya.forms import *

def home(request):
	"""root page for envaya : where all the rules are processed"""
	
	if request.method == 'POST':
		if request.POST["action"] in ["incoming"]:
			try:
				rule_to_apply = BasicRule.objects.get(in_text=request.POST["message"])
				return render_to_response('envaya/index.json' , {'message':rule_to_apply.out_text, 'to':request.POST["from"]},  mimetype="application/json" )
			except:
				pass
		
		


def admin(request):
	"""admin page : where all the rules are set"""

	if request.method == 'POST':
		form=BasicRuleForm(request.POST)
		if form.is_valid():
			form.save()

	form = BasicRuleForm()
	br = BasicRule.objects.all().order_by('-id')
	#return render_to_response('envaya/admin.html' , {'BasicRuleForm':form})

	t = loader.get_template('envaya/admin.html')
	c = RequestContext(request, {'BasicRuleForm':form, 'BasicRule':br})
	return HttpResponse(t.render(c))

templates/envaya/admin.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Django-Envaya Admin page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/static/bootstrap/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="/static/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="/static/bootstrap/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/bootstrap/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/bootstrap/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/bootstrap/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/static/bootstrap/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Django-Envaya Admin</a>
          <!--<div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container" align="center">

      <div class="page-header">
        <h1 align="left">Rules creation <small>Set your rules here</small></h1>
      </div>
      <form action="." method="POST" class="well form-inline"><input id="id_name" type="text" name="name" maxlength="50" placeholder="Name">
	    <input id="id_in_text" type="text" name="in_text" maxlength="150" placeholder="Incoming Text" class="span4">
	    <input id="id_out_text" type="text" name="out_text" maxlength="140" placeholder="Outgoing Text" class="span4">
	    <button type="submit" class="btn btn-primary">Save</button>
	    <button type="reset" class="btn">Cancel</button>
	  </form>
	  <br><br>
	  <div class="page-header">
        <h1 align="left">Rules List <small>Check and Edit your rules here</small></h1>
      </div>

      <table align="left" class="table table-bordered">
      	<thead>
      	  <tr>
      	  	<th>Name</th>
      	  	<th>Incoming</th>
      	  	<th>Outgoing</th>
      	  	<th>Edit</th>
      	  </tr>
      	</thead>
      	<tbody>
        {% for b in BasicRule %}
          <tr>
          	<td>{{ b.name }}</td><td>{{b.in_text}}</td><td>{{b.out_text}}</td><td><a class="btn" href="#"><i class="icon-edit"></i></a> <a class="btn" href="#"><i class="icon-remove"></i></a></td>
          </tr>
        {% endfor %}
      	</tbody>
      </table>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/bootstrap/js/jquery.js"></script>
    <script src="/static/bootstrap/js/bootstrap-transition.js"></script>
    <script src="/static/bootstrap/js/bootstrap-alert.js"></script>
    <script src="/static/bootstrap/js/bootstrap-modal.js"></script>
    <script src="/static/bootstrap/js/bootstrap-dropdown.js"></script>
    <script src="/static/bootstrap/js/bootstrap-scrollspy.js"></script>
    <script src="/static/bootstrap/js/bootstrap-tab.js"></script>
    <script src="/static/bootstrap/js/bootstrap-tooltip.js"></script>
    <script src="/static/bootstrap/js/bootstrap-popover.js"></script>
    <script src="/static/bootstrap/js/bootstrap-button.js"></script>
    <script src="/static/bootstrap/js/bootstrap-collapse.js"></script>
    <script src="/static/bootstrap/js/bootstrap-carousel.js"></script>
    <script src="/static/bootstrap/js/bootstrap-typeahead.js"></script>

  </body>
</html>